apiVersion: v1
kind: Service
metadata:
  name: recco
  namespace: craftista

spec:
  selector:
    app: craftista-rc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  #   nodePort: 30083
  # type: NodePort
  # externalTrafficPolicy: Cluster 
