apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: craftista

spec:
  selector:
    app: craftista-cat
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  #   nodePort: 30081
  # type: NodePort
  # externalTrafficPolicy: Cluster
    
