name: CI
on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  checkchange:
    runs-on: self-hosted
    steps:
      
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

