name: CI
on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  checkchange:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [catalogue, frontend, recommendation, voting]
    steps:
      
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: Install SonarQube Scanner CLI
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-* sonar-scanner
          echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Scan Catalogue
        working-directory: catalogue
        run: sonar-scanner \
          -Dsonar.projectKey=catalogue \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Scan Frontend
        working-directory: frontend
        run: sonar-scanner \
          -Dsonar.projectKey=frontend \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

