name: CI
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k3s/**'
  
  workflow_dispatch:

jobs:
  # SonarQube:
  #   runs-on: self-hosted
  #   strategy:
  #     matrix:
  #       service: [catalogue,frontend,recommendation,voting]
  #   steps:
      
  #     - name: checkout repo
  #       uses: actions/checkout@v4
      
  #     - name: Install SonarQube Scanner CLI
  #       run: |
  #         curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
  #         unzip sonar-scanner.zip
  #         mv sonar-scanner-* sonar-scanner
  #         echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH
  #         pwd

  #     - name: Scan ${{ matrix.service }}
  #       working-directory: ${{ matrix.service }}
  #       run: |
  #         sonar-scanner \
  #         -Dsonar.projectKey=${{ matrix.service }} \
  #         -Dsonar.sources=/home/bha5kar/workspace/actions-runner/_work/craftista/craftista/${{ matrix.service }} \
  #         -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
  #         -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  #     - name: Quality Gate Check
  #       uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
  #       with:
  #         scanMetadataReportFile: ${{ matrix.service }}/.scannerwork/report-task.txt
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  buildpush-image:
    #needs: SonarQube
    runs-on: ubuntu-latest
    strategy:
       matrix:
        service: [catalogue,frontend,recommendation,voting]
    steps:
      

      - name: checkout
        uses: actions/checkout@v4

      - name: login to dockerhub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: setup build
        uses: docker/setup-buildx-action@v3

      - name: build & push
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}

      - name: Update image tag in manifest
          
        run: |
          NEW_TAG=${{ github.sha }}
          pwd
          ls -lrt
          git pull
          sed -i "s|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:$NEW_TAG|" k3s/${{ matrix.service }}/deploy*.yml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k3s/${{ matrix.service }}/deploy*.yml
          git commit -m "Update ${{ matrix.service }} image to $NEW_TAG [skip ci]"
          git push -u origin main

        